#!/bin/bash
set -e

: "${FORGEJO_DB_NAME:=forgejo}"
: "${FORGEJO_DB_USER:=forgejo}"
: "${FORGEJO_DB_PASSWD:=forgejo}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
CREATE USER ${FORGEJO_DB_USER} WITH ENCRYPTED PASSWORD '${FORGEJO_DB_PASSWD}';
CREATE DATABASE ${FORGEJO_DB_NAME} OWNER ${FORGEJO_DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${FORGEJO_DB_NAME}" <<-EOSQL
ALTER SCHEMA public OWNER TO ${FORGEJO_DB_USER};
GRANT ALL ON SCHEMA public TO ${FORGEJO_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${FORGEJO_DB_USER};
EOSQL
